name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - cufflinks
  - folium
  - ipywidgets
  - numpydoc
  - pandas-datareader
  - plotly
  - seaborn
  - voila
  - voila-material
